02-add-gift
Albert-SA/ts-pictures pull request #2
Opened 2023-12-22 18:09 UTC by Albert-SA

2023-12-24 09:54 UTC, andrey-kudinov requested changes

2023-12-24 09:54 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +  destroy: boolean;
`destroy?: boolean;`

2023-12-24 09:54 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +    destroy = false,
`destroy`

2023-12-24 09:54 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +    destroy = false,
не передадим - `undefined`

2023-12-24 09:54 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +      document.querySelectorAll('[data-modal]').forEach(modal => {
```
const modals = document.querySelectorAll('[data-modal]')
modals.forEach(modal => ...)
```

2023-12-24 09:54 UTC, andrey-kudinov commented on src/ts/modules/modals.ts
> +        showSelector.click();
`const isScrollAtBottom = window.scrollY + document.documentElement.clientHeight >= document.documentElement.scrollHeight;`

2023-12-29 17:42 UTC, Albert-SA commented on src/ts/modules/modals.ts
> +    destroy = false,
ok

2023-12-29 17:42 UTC, Albert-SA commented on src/ts/modules/modals.ts
> +      document.querySelectorAll('[data-modal]').forEach(modal => {
ok

2023-12-29 17:42 UTC, Albert-SA commented on src/ts/modules/modals.ts
> +        showSelector.click();
ok

2023-12-29 17:44 UTC, merged